---
name: workflow
description: Create VM and send Email 
enabled: true
entry_point: workflows/workflow.yaml

runner_type: orquesta

parameters:
  Subcription_id:
    type: string
    description: 'Subcription_id of azure' 
    required: true
  Group_Name:
    type: string
    description: 'Group_Name of VM'
    required: true
  Location:
    type: string
    description: 'Location of VM '
    default: master
  VM_Name:
    type: string
    description: 'Name of VM'
    default: production
  Client_Id:
    type: string
    description: Client_Id of azure 
    required: true
  Secret:
    type: string
    description: Secret key of azure  
    required: true
  Tenant_Id:
    type: integer
    description: Tenant_Id of azure 
    required: true
  from:
    type: string
    description: Email Senders name.
    required: true 
